services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=homework_taxi
    ports:
      - "5432:5432"
    volumes:
      - "./homework_postgres_db:/var/lib/postgresql/data:rw"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - "./homework_pgadmin_db:/var/lib/pgadmin:rw"
